"""Add error_message field to videos table

Revision ID: e956d1d234ca
Revises: add_sequences_to_timelines
Create Date: 2026-01-03 13:14:39.605595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e956d1d234ca'
down_revision: Union[str, None] = 'add_sequences_to_timelines'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop saved_clips first (it has foreign key to clips)
    op.drop_index(op.f('idx_saved_clips_clip_id'), table_name='saved_clips')
    op.drop_index(op.f('idx_saved_clips_highlight_id'), table_name='saved_clips')
    op.drop_table('saved_clips')
    # Now drop clips
    op.drop_index(op.f('idx_clips_video_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_column('highlights', 'reason')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.add_column('videos', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_videos_clerk_user_id'), 'videos', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_clerk_user_id'), table_name='videos')
    op.drop_column('videos', 'error_message')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('highlights', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('saved_clips',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('highlight_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('saved_clips_clip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], name=op.f('saved_clips_highlight_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_clips_pkey'))
    )
    op.create_index(op.f('idx_saved_clips_highlight_id'), 'saved_clips', ['highlight_id'], unique=False)
    op.create_index(op.f('idx_saved_clips_clip_id'), 'saved_clips', ['clip_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('end', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('clips_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clips_pkey'))
    )
    op.create_index(op.f('idx_clips_video_id'), 'clips', ['video_id'], unique=False)
    # ### end Alembic commands ###

